baseURL = ""
languageCode = "en-us"
title = "Hugo-Cactus-theme-mod"
theme = "cactus"
copyright = "You" # cactus will use title if copyright is not set
# disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"
hasCJKLanguage = true


# Main menu which appears below site header.
[permalinks]
weekly = "/:year/:slug/"
page = "/:slug/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Weekly"
url = "/weekly"
weight = 2

[[menu.main]]
name = "Others"
url = "/posts"
weight = 3

[[menu.main]]
name = "About"
url = "/tags-wall"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "friendly"
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  enableimgloop = true
  colortheme = "classic" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default

  # Home page settings
  description = "Hugo-cactus-mod by 塔塔"
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 10 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = true # default
    engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
    [params.comments.utterances]
      repo = "<github_username>/<github_reponame>"
      label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
      theme = "github-light"
    [params.comments.cactuscomments]
      siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
      #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
      #serverName = "" # Defaults to cactus.chat
    


